### ISSUE TITLE
on ubuntu 20.04 python is not available

### ISSUE THREAD

**Issue by MAWSpitau** [rebeccamorgan/due#23]
Hi there, 

on ubuntu 20.4 
> $ python 
is not available. Fixed it with this... 

```
#!/usr/bin/env bash

action=$1
flag=$2
python=/usr/bin/python3 # python is no longer awailable on Ubuntu 20.04

shift

[ "$action" = "usage" ] && {
  echo "  Visualize tasks by due date:"
  echo "    due"
  echo "      default behaviour generates a list tasks due today or overdue"
  echo "      Optional argument (integer n) also shows tasks due in next n days."
  echo ""
  exit
}

[ "$action" = "due" ] && {
     $python $(dirname $0)/due.py "$TODO_FILE" $flag
}
```

I don not know if this is clever or not, but it works works for me,

**Comment by ddffnn** [comment]
@MAWSpitau, maybe you can fix this by installing `python-is-python3`.

**Comment by MAWSpitau** [comment]
Thanks for the tipp. Seems like its working!

**Comment by rebecca-owen** [comment]
I've just removed support for Python2 as it is now no longer supported, so you shouldn't need a workaround with the latest commit. Hope that helps!
