### ISSUE TITLE
All tasks appear as overdue

### ISSUE THREAD

**Issue by daedaless** [rebeccamorgan/due#25]
When I run `todo.sh due`, all of the tasks (1 due today, the rest due in the future) appear as `Overdue tasks`. See example output:

```
Overdue tasks:

1 TODO example A due:2020-04-19

3 TODO example B due:2020-04-20

4 TODO example C due:2020-04-21
```

Any ideas? Not sure how to debug this.

**Comment by rebecca-owen** [comment]
Hi camr12,

It looks like these dates are in April - is this issue observed on the current date (2020-05-19)?
