### ISSUE TITLE
todo.actions.d/due Is a directory

### ISSUE THREAD

**Issue by juli-dot-md** [rebeccamorgan/due#3]
Hi! 

When I run todo.sh due I'm getting the following error:

/home/julian/todo.txt_cli/todo.sh: line 878: /home/julian/.todo.actions.d/due: Is a directory

I think the clone command needs a dot at the end so it doesn't create a new directory:

git clone https://github.com/rebeccamorgan/due.git .

**Comment by rebecca-owen** [comment]
Hi Julian,

Can I ask what OS you're using? The subdirectory structure works fine on OS X but not on Ubuntu, that I'm aware of. Cloning directly into .todo_actions.d will work but would cause conflicts with git repositories if you have other add-ons cloned, although this is only a problem for pulling future changes. I'll have a further look at this over the weekend.

Thanks!

**Comment by juli-dot-md** [comment]
Hi! 

I'm indeed using Ubuntu. 

Thanks!

**Comment by juli-dot-md** [comment]
I just found out the I somehow managed to install release 2.9. In 2.10 support for subfolders was added and everything works now. Thanks!
